### PR TITLE
rip agents :skull_and_crossbones: :pray: :100: :skull: :coffin: :zany_face: 

### PR DESCRIPTION
**Pull request by harryjph**

### CODE REVIEW

**Comment by btarifi10** [comment]
Description? 👀

**Review by WillPowellUk — APPROVED** [review]
May they rest in peace. Looks all okay! I am wondering if you would like to wait for lucia's ln/voting PR to be accepted before merging?

**Comment by harryjph** [comment]
It does look like her PR conflicts. I'll leave this one since it's smaller

**Comment by dharmilshah99** [comment]
💀

**Pull request merged**
